name: wt_settings
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/tmcmaster/wt_settings

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  wt_models:
    git: git@github.com:tmcmaster/wt_models.git
  riverpod: ^2.0.2
  logger:
  hooks_riverpod:
  shared_preferences:
  date_time_picker: ^2.1.0
  spring_button: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: