name: wt_settings
description: Components to manage settings using SharedPreferences.
version: 1.0.0+1
homepage: https://github.com/tmcmaster/wt_settings
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

# Scripts to be run with rps
scripts:
  init: flutter pub get
  clean: flutter clean
  refresh: flutter clean; flutter pub get
  test: flutter test
  check: dart analyze
  fix: dart fix --dry-run
  freezed:
    build: dart run build_runner build --delete-conflicting-outputs
  coverage:
    generate: ./bin/generate_coverage.sh
    view: open coverage/html/index.html

dependencies:
  date_time_picker:
    git:
      url: https://github.com/tmcmaster/date_time_picker.git
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  logger: ^1.4.0
  shared_preferences: ^2.2.0
  spring_button: ^2.0.0
  wt_logging:
    git:
      url: https://github.com/tmcmaster/wt_logging.git
  wt_models:
    git:
      url: https://github.com/tmcmaster/wt_models.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true