name: wt_settings
description: Components to manage settings using SharedPreferences.
version: 1.0.0+1
homepage: https://github.com/tmcmaster/wt_settings
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

# Scripts to be run with rps
scripts:
  init: flutter pub get
  clean: flutter clean
  refresh: flutter clean; flutter pub get
  test: flutter test
  check: dart analyze
  fix: dart fix --dry-run
  freezed:
    build: dart run build_runner build --delete-conflicting-outputs
  coverage:
    generate: ./bin/generate_coverage.sh
    view: open coverage/html/index.html
  mockito:
    build: dart run build_runner build --delete-conflicting-outputs

dependencies:
  date_time_picker:
    git:
      url: git@github.com:tmcmaster/date_time_picker.git
  flutter:
    sdk: flutter
  flutter_riverpod:
  logger:
  mockito: any
  number_selector:
  shared_preferences:
  spring_button:
  wt_logging:
    git:
      url: git@github.com:tmcmaster/wt_logging.git
  wt_models:
    git:
      url: git@github.com:tmcmaster/wt_models.git

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

#dependency_overrides:
#  date_time_picker:
#    path: ../../fork/date_time_picker