name: wt_settings
description: Components to manage settings using SharedPreferences.
version: 1.0.0+1
repository: https://github.com/tmcmaster/wt_settings/tree/wix_admin
homepage: https://github.com/tmcmaster/wt_settings
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.29.2'

dependencies:
  date_time_picker:
    git:
      url: git@github.com:tmcmaster/date_time_picker.git
  flutter:
    sdk: flutter
  flutter_riverpod:
  logger:
  mockito: any
  number_selector:
  shared_preferences:
  spring_button:
  wt_logging:
    git:
      url: git@github.com:tmcmaster/wt_logging.git
  wt_models:
    git:
      url: git@github.com:tmcmaster/wt_models.git

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

#dependency_overrides:
#  date_time_picker:
#    path: ../../fork/date_time_picker