name: wt_settings
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/tmcmaster/wt_settings

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  wt_models:
    git: git@github.com:tmcmaster/wt_models.git
  wt_logging:
    git: git@github.com:tmcmaster/wt_logging.git
  riverpod:
  logger:
  hooks_riverpod:
  flutter_hooks:
  shared_preferences:
  date_time_picker:
    git:
      url: https://github.com/tmcmaster/date_time_picker.git
  spring_button:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter: